### ISSUE TITLE
MCMC stochastic results from C++/Python are not compatible

### ISSUE THREAD

**Issue by ielhelw** [ielhelw/MCMC_FOR_AMMSB#1]
On current master, compiling the config options:
CXXFLAGS += -DRANDOM_FOLLOWS_PYTHON -DEFFICIENCY_FOLLOWS_PYTHON
- run python code to record the generated random variables
- run c++ code with the same options submitted to python
- results differ and the C++ code SEGFAULTS before process exits

This has been tested with and without the adjacency list implementation.

**Comment by rfhh** [comment]
Well, you moved the master branch to be the wenzhe-update branch, so this code is a different algorithm than the Python code. There is no Python code for the wenzhe-update stuff.

**Comment by ielhelw** [comment]
Then I will relabel this as a todo since we will eventually need to have equivalent python code.

**Comment by rfhh** [comment]
I remember we had decided to do this python <-> c++ comparison on the older algorithm. It will be harder to be fair if we backport wenzhe-upgrade to python.
