### ISSUE TITLE
Paper plan

### ISSUE THREAD

**Issue by ielhelw** [ielhelw/MCMC_FOR_AMMSB#18]
1- sequential comparison: python vs. seq. vs. multi-thread
  1.1- small: CA-Astro/CA-HepPh
  1.2- medium: com-youtube / web-BerkStan
2- Friendster: find optimal eps/alpha depending on K / m
3- communicate results with Max. Make sure parameter settings and plot matrix makes sense
4- Paper
  4.1- Related work
  4.2- experimental setup

small/medium data sets: CA-Astro/CA-HepPh/com-youtube/com-dblp/com-amazon
- python   VS seq
- seq        VS multi-threaded
- vary K

large: Friendster/Orkut/LiveJournal
- restuls on 64 nodes.
- compare throughput 1-64 nodes

**Comment by rfhh** [comment]
This paper plan is deprecated in favour of splitting into a GPU paper and a Friendster workshop paper.
